In [1]:
import numpy as np  
print(np.__version__)


2.1.0


In [2]:
import sys  
print(sys.executable)

C:\NewFolder\python.exe


In [10]:
import numpy as np  

A = np.full((80, 60), 1)
B = np.full((60, 80), 2)

C = np.dot(A, B)  

print("矩阵A:\n", A)  
print("矩阵B:\n", B)  
print("矩阵A乘矩阵B:\n", C)

矩阵A:
 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
矩阵B:
 [[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
矩阵A乘以矩阵B的结果:
 [[120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]
 ...
 [120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]]
